name: Check Solution
on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      # Устанавливаем Python и зависимости
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"  # или конкретная версия, например "3.10"
      
      # Устанавливаем pytest и другие зависимости (если есть requirements.txt)
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest
      
      # Секретно загружаем тесты
      - name: Download hidden tests
        env:
          TOKEN: ${{ secrets.TESTS_ACCESS_TOKEN }}
        run: |
          if [ -z "$TOKEN" ]; then
            echo "::error::PAT token is not configured!"
            exit 1
          fi
          git clone https://$TOKEN@github.com/${{ github.repository_owner }}/python-practice-tests.git
          # Копируем содержимое tests/, а не саму папку
          cp -r python-practice-tests/tests/. .
      
      # Запускаем тесты
      - name: Run tests
        run: |
          pytest -v
      
      # Очищаем следы
      - name: Cleanup
        run: rm -rf python-practice-tests tests