name: Check Solution
on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: pip install pytest

      - uses: tj-actions/changed-files@v42
        id: changed-files
        with:
          since_last_remote_commit: true  # или другой фильтр

      - name: Determine tests to run
        id: test-filter
        run: |
          TESTS_TO_RUN=()
          
          # Ищем изменения в любых подпапках src/
          changed_files="${{ steps.changed-files.outputs.all_changed_files }}"
          echo "Changed files: ${{ steps.changed-files.outputs.all_changed_files }}"
          for file in ${changed_files}; do
            if [[ $file == src/*/task_*/*.py ]]; then
              category=$(echo "$file" | cut -d'/' -f2)
              task_num=$(echo "$file" | grep -oP 'task_\K\d+')
              test_file="tests/${category}/test_task_${task_num}.py"
              
              if [ -f "$test_file" ]; then
                TESTS_TO_RUN+=("$test_file")
              fi
            fi
          done

          if [ ${#TESTS_TO_RUN[@]} -eq 0 ]; then
            echo "::notice::No specific tasks changed, running all tests"
            TESTS_TO_RUN=("tests/")
          fi

          # Правильное формирование вывода для GitHub Actions
          echo "test_files=${TESTS_TO_RUN[@]}" >> $GITHUB_OUTPUT
          echo "Will run tests for: ${TESTS_TO_RUN[@]}"

      - name: Run tests
        run: pytest -v ${{ steps.test-filter.outputs.test_files }}

      - name: Cleanup
        run: rm -rf tests