name: Check Solution
on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: pip install pytest

      - uses: tj-actions/changed-files@v42
        id: changed-files
        with:
          since_last_remote_commit: true  # или другой фильтр

      - name: Determine tests to run
        id: test-filter
        run: |
          TESTS_TO_RUN=()
          
          # Получаем изменённые файлы как массив
          changed_files_str="${{ steps.changed-files.outputs.all_changed_files }}"
          echo "Raw changed files: '$changed_files_str'"
          
          # Преобразуем строку в массив (учитываем пробелы и переносы)
          IFS=$' \t\n' read -r -a changed_files <<< "$changed_files_str"
          
          for file in "${changed_files[@]}"; do
            echo "Processing file: '$file'"
            
            # Проверяем формат пути (удаляем возможные лишние символы)
            file_clean=$(echo "$file" | tr -d '\r\n')
            
            if [[ "$file_clean" == src/*/task_*/*.py ]]; then
              echo "Matched file pattern: $file_clean"
              category=$(echo "$file_clean" | cut -d'/' -f2)
              task_num=$(echo "$file_clean" | grep -o 'task_[0-9]\+' | cut -d'_' -f2)
              test_file="tests/${category}/test_task_${task_num}.py"
              
              if [ -f "$test_file" ]; then
                echo "Found test file: $test_file"
                TESTS_TO_RUN+=("$test_file")
              else
                echo "Test file not found: $test_file"
              fi
            fi
          done

          if [ ${#TESTS_TO_RUN[@]} -eq 0 ]; then
            echo "::notice::No specific tasks changed, running all tests"
            TESTS_TO_RUN=("tests/")
          fi

          echo "test_files=${TESTS_TO_RUN[*]}" >> $GITHUB_OUTPUT
          echo "Will run tests for: ${TESTS_TO_RUN[*]}"

      - name: Run tests
        run: pytest -v ${{ steps.test-filter.outputs.test_files }}

      - name: Cleanup
        run: rm -rf tests