name: Check Solution
on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: pip install pytest

      - uses: tj-actions/changed-files@v42
        id: changed-files
        with:
          since_last_remote_commit: true  # или другой фильтр

      - name: Determine tests to run
        id: test-filter
        run: |
          TESTS_TO_RUN=()
          
          # Получаем изменённые файлы как массив (с очисткой)
          changed_files_str=$(echo "${{ steps.changed-files.outputs.all_changed_files }}" | tr -d '\r\n')
          IFS=' ' read -r -a changed_files <<< "$changed_files_str"
          
          for file in "${changed_files[@]}"; do
            echo "Processing file: '$file'"
            
            if [[ "$file" == src/*/task_*/*.py ]]; then
              # Очищаем путь и извлекаем данные
              file_clean=$(echo "$file" | xargs)  # Удаляем все пробелы/переносы
              category=$(echo "$file_clean" | cut -d'/' -f2)
              task_num=$(echo "$file_clean" | grep -o 'task_[0-9]\+' | cut -d'_' -f2 | tr -d '[:space:]')
              test_file="tests/${category}/test_task_${task_num}.py"
              
              echo "Checking test file: $test_file"
              if [ -f "$test_file" ]; then
                TESTS_TO_RUN+=("$test_file")
              else
                echo "::error::Test file not found: $test_file"
              fi
            fi
          done

          if [ ${#TESTS_TO_RUN[@]} -eq 0 ]; then
            echo "::notice::No specific tasks changed, running all tests"
            TESTS_TO_RUN=("tests/")
          fi

          echo "test_files=${TESTS_TO_RUN[*]}" >> $GITHUB_OUTPUT
          echo "Will run tests for: ${TESTS_TO_RUN[*]}"

      - name: Run tests
        run: pytest -v ${{ steps.test-filter.outputs.test_files }}

      - name: Cleanup
        run: rm -rf tests